fallback = ''

[matching]
'discord' = ''
'balena-etcher' = ''
'Steam' = ''
'Postman' = ''
'Insomnia' = ''
'1Password' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'/rust/' = ''
'Alacritty' = ''
'kitty' = ''
'obsidian' = '' 
'/Bible/' = ''
'com.github.johnfactotum.Foliate' = ''
